spring.application.name=SpringBootBestPratices
# Set logging levels
logging.level.org.springframework=INFO
logging.level.com.praveen=DEBUG
logging.file.name=logs/application.log # Save logs to a file
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n # Console log format
